137 frontend review scale functionality
fsdevWebmaster/proyecto-final pull request #144
Opened 2023-10-06 19:41 UTC by fsdevWebmaster

It is important to discuss this PR. 
I was so big because the backend connection needs. Some long frontend changes was needed. 
This PR includes fixing ticket # 140.

2023-10-06 19:43 UTC, fsdevWebmaster commented
This PR includes fixing ticket #141 too.

2023-10-06 19:44 UTC, fsdevWebmaster commented
Minor merge conflict fixed.

2023-10-06 20:08 UTC, jotaZuniga commented on frontend/src/components/Search/SearchController.ts
> +    // const found = mockContainers.filter(item => item.containerNumber.includes(value))
removamos codigo comentado que no usemos...

2023-10-06 20:08 UTC, jotaZuniga commented on frontend/src/components/Search/SearchController.ts
> +    // setContainers([])
removamos codigo comentado que no usemos...

2023-10-06 20:09 UTC, jotaZuniga commented on frontend/src/pages/Gate/Gate.tsx
> +    console.log("TODO: update driver's UI", created)
Quitemos logs de consola

2023-10-06 20:11 UTC, jotaZuniga commented on frontend/src/pages/Gate/Gate.tsx
> +    setActualStep(toJS(actualStep))
actualStep podria ser undefined y el metodo toJS daria error. Hay que validar que al menos tengamos el actualStep

2023-10-06 20:13 UTC, jotaZuniga commented on frontend/src/pages/Scale/Scale.tsx
> +      setActualStep(actualStep)
Misma situacion aca que la validacion de si actualStep existe

2023-10-06 20:14 UTC, jotaZuniga commented on frontend/src/services/api/yardApi.ts
> +    login(email: string, password:string): Promise<any> {
Que hace la funcion login en Yard?... se necesita realmente

2023-10-06 20:14 UTC, jotaZuniga commented on frontend/src/stores/ConfigStore.ts
> +      console.log(resp)
eliminemos logs

2023-10-06 20:15 UTC, jotaZuniga commented on frontend/src/stores/ConfigStore.ts
> +      // this.setCurrentStep(resp);
eliminemos lineas que no necesitamos y estan comentadas

2023-10-06 20:15 UTC, jotaZuniga commented on frontend/src/stores/JourneyStore.ts
> +// import { stepApi } from "@services/api/stepApi";
eliminemos lineas comentadas

2023-10-06 20:16 UTC, jotaZuniga commented on frontend/src/stores/StepStore.ts
> +  stepsList: StepModel[] = []
stepsList esta tambien creado dentro del JourneyStore... porque crearlo aca tambien?... solo deberiamos utilizarlo en 1 solo store

2023-10-06 20:17 UTC, jotaZuniga requested changes
Leer el feedback de los cambios

2023-10-06 21:00 UTC, fsdevWebmaster commented on frontend/src/stores/StepStore.ts
> +  stepsList: StepModel[] = []
Eliminado de journeyStore

2023-10-06 22:58 UTC, FranJimenezQ approved these changes
Ok

2023-10-07 22:59 UTC, jotaZuniga approved these changes

2023-10-09 22:48 UTC, merged